window.ELEVA_DATA = {
  fragrances: {
    "ADRENALINE": { family: "Floral-acuática", desc: "Frescura marina con naranja y pomelo, corazón floral y fondo de almizcle y vainilla. Aporta energía limpia y sofisticada.", image: "Marca activa, moderna y elegante." },
    "AIR FRESH": { family: "Floral-afrutada", desc: "Jazmín, rosa y menta con pera, manzana y notas marinas. Sensación de pureza, ligereza y bienestar.", image: "Imagen limpia, abierta y acogedora." },
    "ALOE": { family: "Fresca-verde", desc: "Notas verdes, menta y aloe con manzana, jazmín, melón, cedro y sándalo. Natural, renovadora y suave.", image: "Naturalidad, confianza y frescura saludable." },
    "AMBER - VANILLA": { family: "Oriental-afrutada", desc: "Almendra y melocotón con madera blanca, violeta, vainilla y haba tonka. Cálida, envolvente y confortable.", image: "Calidez premium, cercanía y sensación elegante." },
    "AMBER WOOD": { family: "Oriental-amaderada", desc: "Naranja amarga, flores blancas, violeta, canela, cedro, ámbar y sándalo. Cálida y seductora.", image: "Sofisticación, carácter y seguridad." },
    "AMETHYST": { family: "Floral-amaderada", desc: "Pomelo y notas verdes con iris, rosa y maderas exóticas. Elegante, misteriosa y floral.", image: "Imagen refinada, femenina y exclusiva." },
    "ANTI - TABAC": { family: "Fresca-aromática", desc: "Alcanfor, bergamota, notas marinas, manzana, anís y rosa. Ideal para enmascarar olor a humo.", image: "Limpieza, renovación y control de olores." },
    "AROMATIC CITRUS": { family: "Fresca-cítrica", desc: "Limón y menta con bergamota, rosa, cedro y bayas. Luminosa, revitalizante y natural.", image: "Energía, dinamismo y frescura inmediata." },
    "AROMATIC MINT": { family: "Fresca-aromática", desc: "Eucalipto, hierbabuena, lavanda, romero, tomillo e ylang-ylang. Purificante y revitalizante.", image: "Ambiente limpio, activo y despejado." },
    "AURA DE FLEUR": { family: "Floral-verde", desc: "Naranja, lavanda, césped, bergamota, flores blancas y almizcle. Evoca un jardín fresco y vivo.", image: "Naturalidad luminosa y bienestar sereno." },
    "BAKERY": { family: "Gourmande", desc: "Mantequilla, fruta verde, vainilla, miel, caramelo y almendra. Aroma de repostería recién hecha.", image: "Cercanía, apetito y sensación artesanal." },
    "BAMBOO FLOWERS": { family: "Floral-acuática", desc: "Hojas de violeta, notas marinas, lirio de los valles, miel y jazmín. Serena, delicada y acuática.", image: "Calma, equilibrio y bienestar premium." },
    "BLACK AMBER": { family: "Oriental-amaderada", desc: "Naranja, lavanda, gaiac, ámbar, sándalo y cedro. Cálida, íntima y con fondo elegante.", image: "Lujo discreto, misterio y confort." },
    "BLACK OUD": { family: "Amaderada-oriental", desc: "Acordes intensos de oud, cítricos y maderas. Aroma profundo para espacios con personalidad.", image: "Exclusividad, fuerza y carácter sofisticado." },
    "BLACKBERRY": { family: "Afrutada", desc: "Perfil dulce y jugoso de frutos rojos. Aporta un ambiente joven, alegre y apetecible.", image: "Vitalidad, dulzura y cercanía." },
    "BLUE SILVER": { family: "Colonia-amaderada", desc: "Sensación limpia, elegante y masculina, pensada para espacios sobrios y profesionales.", image: "Confianza, estilo y profesionalidad." },
    "BREATHE": { family: "Fresca", desc: "Aroma despejado y respirable, con sensación de aire limpio y amplitud.", image: "Bienestar, calma y espacio cuidado." },
    "BURNED WOOD": { family: "Amaderada", desc: "Notas de leña, humo y madera cálida. Intensa, gastronómica y envolvente.", image: "Autenticidad, carácter y cocina de brasa." },
    "CAKE": { family: "Gourmande", desc: "Dulce de pastelería con matiz cremoso. Ideal para despertar apetito.", image: "Placer, cercanía y tentación." },
    "CALABRIA": { family: "Cítrica", desc: "Aroma fresco inspirado en cítricos mediterráneos. Vital y luminoso.", image: "Energía mediterránea y limpieza." },
    "CANNES": { family: "Elegante", desc: "Fragancia sofisticada para entornos premium y de atención al cliente.", image: "Estilo, exclusividad y atención al detalle." },
    "CAPPUCCINO": { family: "Gourmande", desc: "Notas de café y crema. Cálida, apetecible y confortable.", image: "Hospitalidad, pausa y sabor." },
    "CARAMEL DREAMS": { family: "Gourmande", desc: "Caramelo dulce y envolvente. Genera un ambiente cálido y tentador.", image: "Dulzura, recuerdo y experiencia acogedora." },
    "CEDAR ORANGE": { family: "Cítrica-amaderada", desc: "Naranja luminosa con fondo de cedro. Equilibra frescura y estructura.", image: "Profesionalidad fresca y moderna." },
    "CEDAR SANTAL": { family: "Amaderada", desc: "Cedro y sándalo con efecto cálido, seco y elegante.", image: "Seriedad, lujo natural y estabilidad." },
    "CHEWING GUM": { family: "Gourmande-afrutada", desc: "Aroma dulce y divertido de chicle. Funciona en espacios infantiles o juveniles.", image: "Diversión, juventud y cercanía." },
    "CITRONELLE": { family: "Cítrica-aromática", desc: "Citronela fresca con carácter natural. Adecuada para ambientes exteriores o de verano.", image: "Naturalidad y frescor funcional." },
    "CLEAN": { family: "Fresca", desc: "Sensación directa de limpieza, ropa recién lavada y ambiente ordenado.", image: "Higiene, confianza y pulcritud." },
    "COCOON": { family: "Confort", desc: "Aroma suave y envolvente para crear sensación de refugio.", image: "Comodidad, calma y bienestar." },
    "COLOMBIAN COFFEE": { family: "Gourmande", desc: "Café intenso y tostado. Perfecto para cafeterías y zonas de descanso.", image: "Tradición, energía y hospitalidad." },
    "COTTON": { family: "Limpia", desc: "Algodón suave y fresco, con sensación de ropa limpia.", image: "Pureza, suavidad y cuidado." },
    "CRISP CUCUMBER MELON": { family: "Fresca-afrutada", desc: "Pepino crujiente y melón jugoso. Muy refrescante y ligera.", image: "Frescura joven y natural." },
    "CUT GRASS": { family: "Verde", desc: "Césped recién cortado. Natural, fresco y vital.", image: "Exterior, naturaleza y sensación sostenible." },
    "EUCALYPTUS": { family: "Aromática", desc: "Eucalipto limpio e intenso. Despeja el ambiente y aporta sensación higiénica.", image: "Salud, respiración y limpieza." },
    "FIG": { family: "Frutal-verde", desc: "Higo verde con matiz natural y mediterráneo.", image: "Elegancia natural y calma." },
    "FRESH": { family: "Fresca", desc: "Frescura versátil para espacios con tránsito y necesidad de ambiente limpio.", image: "Orden, frescura y facilidad." },
    "GREEN TEA": { family: "Verde", desc: "Té verde suave, equilibrado y limpio. Muy versátil en espacios profesionales.", image: "Serenidad, equilibrio y frescura premium." },
    "GUMMIES": { family: "Gourmande-afrutada", desc: "Gominolas dulces y alegres. Aroma lúdico para público joven.", image: "Diversión, color y energía." },
    "HARMONY": { family: "Equilibrada", desc: "Fragancia redonda y tranquila para espacios que buscan confort.", image: "Equilibrio, calma y bienestar." },
    "LAVENDER": { family: "Aromática", desc: "Lavanda clásica, calmante y natural. Ideal para descanso, salud y bienestar.", image: "Relajación, confianza y cuidado." },
    "LEMON": { family: "Cítrica", desc: "Limón limpio y chispeante. Aporta frescor inmediato y sensación higiénica.", image: "Limpieza, vitalidad y rapidez." },
    "LIME GREEN": { family: "Cítrica-verde", desc: "Lima verde fresca, ácida y energética.", image: "Modernidad, dinamismo y frescura." },
    "MOUNTAIN MIST": { family: "Fresca", desc: "Bruma de montaña, aire limpio y sensación natural.", image: "Amplitud, tranquilidad y frescor." },
    "NEUTRALIZADOR": { family: "Funcional", desc: "Diseñado para reducir olores no deseados y dejar una sensación limpia.", image: "Higiene, control y confianza." },
    "ORANGE BLOSSOM": { family: "Floral-cítrica", desc: "Azahar luminoso, floral y elegante.", image: "Optimismo, delicadeza y elegancia." },
    "ORANGE CINNAMON": { family: "Cítrica-especiada", desc: "Naranja con canela, cálida y acogedora.", image: "Hogar, temporada y cercanía." },
    "ORANGE WOOD": { family: "Cítrica-amaderada", desc: "Naranja con maderas, fresca y con presencia.", image: "Equilibrio entre energía y solidez." },
    "PASSION FRUIT": { family: "Tropical", desc: "Fruta de la pasión intensa, tropical y jugosa.", image: "Alegría, verano y exotismo." },
    "RED PASSION": { family: "Afrutada", desc: "Frutal intenso, dulce y llamativo.", image: "Pasión, energía y recuerdo." },
    "SANDALWOOD": { family: "Amaderada", desc: "Sándalo cremoso, cálido y persistente.", image: "Lujo, serenidad y profundidad." },
    "SENSATION": { family: "Fresca", desc: "Aroma vibrante y agradable para generar impacto positivo.", image: "Dinamismo y experiencia memorable." },
    "SPA": { family: "Fresca-relajante", desc: "Perfil wellness pensado para balnearios, spas y zonas de descanso.", image: "Relax, bienestar y desconexión." },
    "SWEET CHERRY": { family: "Afrutada", desc: "Cereza dulce y juvenil.", image: "Alegría, dulzura y cercanía." },
    "TALCUM POWDER": { family: "Limpia", desc: "Talco suave, limpio y familiar.", image: "Cuidado, ternura y seguridad." },
    "TROPICAL MANGO": { family: "Tropical", desc: "Mango jugoso, dulce y solar.", image: "Vacaciones, energía y optimismo." },
    "VANILLA": { family: "Gourmande", desc: "Vainilla cálida, dulce y confortable.", image: "Calidez, comodidad y recuerdo." },
    "VERBENA": { family: "Cítrica-verde", desc: "Verbena fresca, limpia y natural.", image: "Frescura sencilla y bienestar." },
    "WAVE FRESH": { family: "Acuática", desc: "Ola fresca con sensación marina y limpia.", image: "Amplitud, pureza y frescor." },
    "WHITE BUBBLES": { family: "Limpia", desc: "Burbujeante, fresca y luminosa.", image: "Optimismo, limpieza y modernidad." },
    "WHITE COCONUT": { family: "Tropical", desc: "Coco blanco suave, cremoso y veraniego.", image: "Relax, playa y suavidad." },
    "WHITE LOTUS": { family: "Floral-acuática", desc: "Loto blanco, delicado, limpio y sereno.", image: "Calma, pureza y elegancia." },
    "WHITE TEA": { family: "Verde", desc: "Té blanco suave y refinado.", image: "Elegancia tranquila y pureza." },
    "WILD GRAPE": { family: "Afrutada", desc: "Uva silvestre, dulce y vivaz.", image: "Juventud, frescura y energía." },
    "WILD HYACINTH BREEZE": { family: "Floral", desc: "Jacinto floral y fresco con efecto brisa.", image: "Delicadeza, naturaleza y serenidad." },
    "WOMAN": { family: "Colonia femenina", desc: "Perfil femenino, limpio y elegante.", image: "Cuidado, estilo y suavidad." }
  },

  businesses: [
    { name: "Agencias de viaje, Tiendas de playa", aliases: ["agencia de viaje", "viajes", "tienda de playa", "playa"], families: "Fresca cítrica, acuática, aromática y afrutada", notes: "Bronceador, mango, coco", fragrances: ["ADRENALINE", "ANTI - TABAC", "AROMATIC CITRUS", "CALABRIA", "CITRONELLE", "TROPICAL MANGO", "WHITE COCONUT", "WAVE FRESH"] },
    { name: "Albergues, BnB, Residencias", aliases: ["albergue", "bnb", "residencia", "hostal"], families: "Fresca aromática y verde", notes: "Cedro, lavanda", fragrances: ["AIR FRESH", "ALOE", "ANTI - MOSQUITOES", "AROMATIC MINT", "CUT GRASS", "GREEN TEA", "LAVENDER", "VERBENA"] },
    { name: "Almacenes, Talleres, Naves industriales", aliases: ["almacen", "taller", "nave industrial", "industria"], families: "Fresca afrutada y cítrica", notes: "Limón, cereza, pomelo, piña", fragrances: ["AROMATIC CITRUS", "CALABRIA", "FRESH", "LEMON", "LIME GREEN", "SICILIAN SUMMER", "SWEET CHERRY"] },
    { name: "Aseos, W.C., Vestuarios", aliases: ["aseo", "wc", "baño", "vestuario"], families: "Fresca y gourmande frutal", notes: "Aromas de limpieza y fruta", fragrances: ["ADRENALINE", "ALOE", "ANTI - TABAC", "APPLE CRUNCH", "AROMATIC CITRUS", "CLEAN", "NEUTRALIZADOR", "WAVE FRESH"] },
    { name: "Asesorías, Consultorías, Gestorías, Notarías", aliases: ["asesoria", "consultoria", "gestoria", "notaria", "despacho"], families: "Amaderada, chipre y colonia", notes: "Bambú, bergamota", fragrances: ["AROMATIC CITRUS", "BAMBOO FLOWERS", "BLACK OUD", "BLUE SILVER", "CALABRIA", "CEDAR SANTAL", "GREEN TEA", "HARMONY"] },
    { name: "Balnearios, Spas", aliases: ["balneario", "spa", "wellness"], families: "Fresca acuática, verde, aromática y oriental", notes: "Spa, césped, cedro, eucalipto, manzana, lavanda, rosa", fragrances: ["ADRENALINE", "ALOE", "AMBER - VANILLA", "AMBER WOOD", "AROMATIC MINT", "AURA DE FLEUR", "BAMBOO FLOWERS", "SPA"] },
    { name: "Bibliotecas", aliases: ["biblioteca", "libreria", "sala lectura"], families: "Amaderada, fougère, oriental y fresca cítrica", notes: "Roble, tierra, café", fragrances: ["AMBER - VANILLA", "AMBER WOOD", "AROMATIC CITRUS", "BLACK OUD", "CARIBBEAN VETIVER", "COLOMBIAN COFFEE", "EARTH"] },
    { name: "Bodas", aliases: ["boda", "eventos", "celebracion"], families: "Chipre, floral y fougère", notes: "Césped, azahar, rosa", fragrances: ["ADRENALINE", "AIR FRESH", "AMETHYST", "BAMBOO FLOWERS", "FLORAL HARMONY", "ORANGE BLOSSOM", "WHITE LOTUS", "WHITE ROSE"] },
    { name: "Bodegas", aliases: ["bodega", "vino", "enoteca"], families: "Fresca aromática y amaderada", notes: "Roble", fragrances: ["ANTI - TABAC", "BLACK OUD", "CEDAR SANTAL", "EARTH", "LAVENDER", "LEGEND", "ORANGE WOOD"] },
    { name: "Cafeterías", aliases: ["cafeteria", "cafe", "coffee shop"], families: "Gourmande", notes: "Pastel, manzana, bollería, clavo, caramelo, café", fragrances: ["APPLE CRUNCH", "BAKERY", "CAKE", "CAPPUCCINO", "CARAMEL DREAMS", "COLOMBIAN COFFEE", "ORANGE CINNAMON", "VANILLA"] },
    { name: "Casas rurales", aliases: ["casa rural", "rural", "hotel rural"], families: "Fresca aromática, verde y fougère", notes: "Cedro, lavanda", fragrances: ["AIR FRESH", "ALOE", "AROMATIC MINT", "AURA DE FLEUR", "CUT GRASS", "EUCALYPTUS", "GREEN TEA", "LAVENDER"] },
    { name: "Centros de negocio", aliases: ["centro de negocio", "coworking", "oficina"], families: "Amaderada, colonia y fresca cítrica", notes: "Ambiente profesional", fragrances: ["AROMATIC CITRUS", "BLACK OUD", "BLUE SILVER", "CALABRIA", "CEDAR SANTAL", "DOUBLE CITRUS", "HARMONY"] },
    { name: "Centros de salud", aliases: ["centro de salud", "consulta", "ambulatorio"], families: "Fresca acuática y verde", notes: "Césped, talco", fragrances: ["ADRENALINE", "ALOE", "ANTI - TABAC", "AROMATIC MINT", "BREATHE", "CLEAN", "EUCALYPTUS", "TALCUM POWDER"] },
    { name: "Centros fisioterapia", aliases: ["fisioterapia", "fisio", "masaje"], families: "Fresca acuática, aromática, verde y oriental", notes: "Bambú, eucalipto, menta, talco", fragrances: ["ADRENALINE", "ALOE", "AMBER - VANILLA", "AROMATIC MINT", "BAMBOO FLOWERS", "BREATHE", "EUCALYPTUS", "TALCUM POWDER"] },
    { name: "Clínicas dentales", aliases: ["clinica dental", "dentista", "odontologia"], families: "Fresca acuática, verde y floral", notes: "Manzana, bambú, menta", fragrances: ["ADRENALINE", "AIR FRESH", "ALOE", "APPLE CRUNCH", "AROMATIC MINT", "BAMBOO FLOWERS", "CLEAN", "EUCALYPTUS"] },
    { name: "Clínicas estética", aliases: ["clinica estetica", "estetica", "medicina estetica"], families: "Fresca y floral", notes: "Manzana, bambú, menta", fragrances: ["ADRENALINE", "AIR FRESH", "ALOE", "AMETHYST", "AURA DE FLEUR", "BAMBOO FLOWERS", "CLEAN", "WHITE LOTUS"] },
    { name: "Clínicas veterinarias", aliases: ["clinica veterinaria", "veterinario", "mascotas"], families: "Fresca verde, aromática y floral", notes: "Césped", fragrances: ["AIR FRESH", "ALOE", "ANTI - MOSQUITOES", "AROMATIC MINT", "AURA DE FLEUR", "CUT GRASS", "EUCALYPTUS", "NEUTRALIZADOR"] },
    { name: "Colegios, Institutos, Centros de formación, Academias", aliases: ["colegio", "instituto", "academia", "centro de formacion"], families: "Fresca cítrica y afrutada", notes: "Hierbabuena, bergamota, cola", fragrances: ["APPLE CRUNCH", "AROMATIC CITRUS", "BLACKBERRY", "CHEWING GUM", "FRESH", "GREEN TEA", "GUMMIES", "LEMON"] },
    { name: "Concesionarios de vehículos", aliases: ["concesionario", "vehiculos", "coches", "automovil"], families: "Amaderada, colonia, chipre y cuero", notes: "Césped", fragrances: ["AMBER WOOD", "BLACK OUD", "BLUE SILVER", "CEDAR SANTAL", "LEATHER OUD", "ORANGE WOOD", "SANDALWOOD"] },
    { name: "Entidades bancarias, Servicios financieros", aliases: ["banco", "bancaria", "servicios financieros", "financiera"], families: "Amaderada, chipre, colonia y fresca cítrica", notes: "Bambú, ozono, pomelo", fragrances: ["ADRENALINE", "AROMATIC CITRUS", "BAMBOO FLOWERS", "BLACK OUD", "BLUE SILVER", "CEDAR SANTAL", "GREEN TEA"] },
    { name: "Panaderías, Pastelerías", aliases: ["panaderia", "pasteleria", "obrador"], families: "Gourmande y fresca afrutada", notes: "Pastel, manzana, bollería, caramelo", fragrances: ["APPLE CRUNCH", "BAKERY", "BLACKBERRY", "CAKE", "CAPPUCCINO", "CARAMEL DREAMS", "COLOMBIAN COFFEE", "VANILLA"] },
    { name: "Papelerías", aliases: ["papeleria", "material oficina"], families: "Fresca aromática, cítrica, verde, floral y oriental", notes: "Bambú", fragrances: ["AIR FRESH", "ALOE", "AMBER - VANILLA", "AMBER WOOD", "AMETHYST", "BAMBOO FLOWERS", "GREEN TEA"] },
    { name: "Peluquerías, Salones de Belleza, Barberías, Centros de Belleza", aliases: ["peluqueria", "barberia", "salon belleza", "centro belleza"], families: "Chipre, floral y oriental", notes: "Jazmín, melón, té", fragrances: ["AIR FRESH", "AMBER - VANILLA", "AMBER WOOD", "AMETHYST", "BAMBOO FLOWERS", "GREEN TEA", "WHITE LOTUS", "WOMAN"] },
    { name: "Pubs", aliases: ["pub", "bar musical", "discoteca"], families: "Amaderada, fougère, chipre, colonia y gourmand", notes: "Cola, mojito", fragrances: ["AROMATIC MINT", "BLACKBERRY", "BLUE SILVER", "CANNES", "BLACK OUD", "ANTI - TABAC", "RED PASSION"] },
    { name: "Resorts", aliases: ["resort", "hotel", "complejo turistico"], families: "Amaderada, colonia, fresca acuática, aromática y floral", notes: "Coco", fragrances: ["ADRENALINE", "AIR FRESH", "AMETHYST", "ANTI - MOSQUITOES", "BAMBOO FLOWERS", "WHITE COCONUT", "SPA"] },
    { name: "Restaurantes", aliases: ["restaurante", "hosteleria", "comedor"], families: "Amaderada, fresca aromática y chipre", notes: "Albahaca", fragrances: ["BLUE SILVER", "CANNES", "CEDAR SANTAL", "CITRONELLE", "GREEN TEA", "ORANGE WOOD", "VERBENA"] },
    { name: "Restaurantes de comida rápida", aliases: ["comida rapida", "fast food", "hamburgueseria"], families: "Fresca aromática, chipre y gourmande", notes: "Leña, humo", fragrances: ["APPLE CRUNCH", "BAKERY", "BLACKBERRY", "BURNED WOOD", "CARAMEL DREAMS", "LEMON", "NEUTRALIZADOR"] },
    { name: "Ropa de hombre", aliases: ["ropa hombre", "moda hombre", "tienda hombre"], families: "Colonia masculina y amaderada", notes: "Roble", fragrances: ["AMBER WOOD", "BLACK OUD", "BLUE SILVER", "CEDAR SANTAL", "LEATHER OUD", "SANDALWOOD", "SAVAGE"] },
    { name: "Ropa de mujer", aliases: ["ropa mujer", "moda mujer", "boutique mujer"], families: "Chipre, colonia femenina y floral", notes: "Azahar, bambú, rosa", fragrances: ["AIR FRESH", "AMETHYST", "BAMBOO FLOWERS", "ORANGE BLOSSOM", "WHITE LOTUS", "WHITE ROSE", "WOMAN"] },
    { name: "Ropa interior", aliases: ["ropa interior", "lenceria"], families: "Chipre, floral y fresca acuática", notes: "Fresa, jazmín, rosa", fragrances: ["AMETHYST", "BAMBOO FLOWERS", "JASMINE", "RED PASSION", "ROSA", "WHITE LOTUS", "WILD HYACINTH BREEZE"] },
    { name: "Ropa joven femenina", aliases: ["ropa joven femenina", "moda joven mujer"], families: "Chipre, colonia femenina, unisex, fresca cítrica y floral", notes: "Moda joven", fragrances: ["AIR FRESH", "BLACKBERRY", "CHEWING GUM", "GUMMIES", "RED PASSION", "SWEET CHERRY", "WILD GRAPE"] },
    { name: "Ropa joven masculina", aliases: ["ropa joven masculina", "moda joven hombre"], families: "Colonia masculina, unisex, fresca cítrica y amaderada", notes: "Cuero", fragrances: ["AROMATIC CITRUS", "BLUE SILVER", "CEDAR SANTAL", "LEATHER OUD", "LIME GREEN", "ORANGE WOOD", "SAVAGE"] },
    { name: "Ropa joven unisex", aliases: ["ropa joven unisex", "moda joven", "streetwear"], families: "Chipre, colonia unisex, fresca cítrica y floral", notes: "Juventud y frescura", fragrances: ["ADRENALINE", "AROMATIC CITRUS", "BAMBOO FLOWERS", "GREEN TEA", "LIME GREEN", "RED PASSION", "WHITE BUBBLES"] },
    { name: "Ropa y artículos para bebés", aliases: ["bebes", "ropa bebe", "articulos bebe", "tienda bebe"], families: "Chipre, colonia bebé, fresca afrutada y floral", notes: "Chicle, talco, colonia infantil, mora, fresa, cereza", fragrances: ["AIR FRESH", "AMETHYST", "BAMBOO FLOWERS", "CHEWING GUM", "TALCUM POWDER", "SWEET CHERRY", "WHITE LOTUS"] },
    { name: "Salones de juegos, Casinos", aliases: ["casino", "salon de juegos", "juegos"], families: "Amaderada, fresca cítrica, acuática y verde", notes: "Césped, mar", fragrances: ["ADRENALINE", "ALOE", "ANTI - TABAC", "AROMATIC CITRUS", "AROMATIC MINT", "BLACK OUD", "BLUE SILVER"] },
    { name: "Tanatorios", aliases: ["tanatorio", "funeraria"], families: "Floral y amaderada", notes: "Rosa, madera balsámica", fragrances: ["AIR FRESH", "AMETHYST", "BAMBOO FLOWERS", "BLACK OUD", "BLUE SILVER", "CEDAR SANTAL", "WHITE ROSE"] },
    { name: "Tatuajes", aliases: ["tatuaje", "tattoo", "estudio tatuaje"], families: "Fresca acuática, verde, aromática y oriental", notes: "Cuero", fragrances: ["ALOE", "AMBER - VANILLA", "AMBER WOOD", "BLACK AMBER", "BLACK OUD", "LEATHER OUD", "SANDALWOOD"] },
    { name: "Tiendas de alimentación", aliases: ["tienda alimentacion", "alimentacion", "supermercado", "fruteria"], families: "Fresca aromática y gourmande", notes: "Albahaca", fragrances: ["APPLE CRUNCH", "BAKERY", "CAKE", "CAPPUCCINO", "CARAMEL DREAMS", "CITRONELLE", "LEMON"] },
    { name: "Tiendas de bricolaje, de jardinería y de camping", aliases: ["bricolaje", "jardineria", "camping", "garden"], families: "Fresca verde", notes: "Césped", fragrances: ["ALOE", "AROMATIC CITRUS", "AROMATIC MINT", "AURA DE FLEUR", "BREATHE", "CUT GRASS", "GREEN TEA"] },
    { name: "Tiendas decoración", aliases: ["decoracion", "muebles", "interiorismo"], families: "Oriental, fougère, chipre y colonia femenina", notes: "Vainilla", fragrances: ["AMBER - VANILLA", "AMBER WOOD", "AROMATIC MINT", "BLACK AMBER", "BLACK OUD", "CEDAR SANTAL", "VANILLA"] }
  ]
};
